### ISSUE TITLE
Compiling selectize.bootstrap4.scss to css?

### ISSUE THREAD

**Issue by martinbaste** [papakay/selectize-bootstrap-4-style#1]
Thanks for making this. Probably a basic question, but I tried multiple things with no success.

I'm getting "Undefined variable: \"$input-btn-line-height\"." when compiling. I'm assuming there is some bootstrap dependency I'm missing. 

Would it be possible to add a short 'getting started' section to the readme.md?

**Comment by papakay** [comment]
Hello @martinbaste so sorry about the issue. 
**$input-btn-line-height** is a variable specified in the bootstrap4 **_variables.scss**. 

Please also ensure you are using bootstrap v4.0.0-beta.2

I will add a short getting started section shortly. Thanks.

**Comment by martinbaste** [comment]
Thanks! I got it to work now. The readme update was really helpful. Issue fixed.
