### ISSUE TITLE
input group problem

### ISSUE THREAD

**Issue by bahramhasanov** [papakay/selectize-bootstrap-4-style#4]
I tried to use plugin in input-group. and it does not work properly

**Comment by bahramhasanov** [comment]
![image](https://user-images.githubusercontent.com/15985337/37702252-694a24b0-2d0b-11e8-845a-8362a31e4732.png)

**Comment by papakay** [comment]
I've tried locally and everything works fine. Please you put a codepen or a fiddle so I can help further. Thanks.

**Comment by bahramhasanov** [comment]
You can check link below 
https://codepen.io/bahramhasanov/project/editor/AeYGGb

**Comment by papakay** [comment]
I have pushed a demo page to indicate this. Please check the /dist folder.

Thanks.

**Comment by bahramhasanov** [comment]
Thanks. 
Problem was a bootstrap4 version

**Comment by papakay** [comment]
You are welcome. I'm happy it's resolved now.
