### ISSUE TITLE
Is-invalid class not showing.

### ISSUE THREAD

**Issue by juanch0x** [papakay/selectize-bootstrap-4-style#6]
Hello!
I'm working with `Selectize` for the first time, and I really liked the plugin and bootstrap style 4, I'm just having a problem with the `is-invalid` class after validating the form, it just is not shown, the div with `invalid -feedback` works perfect, but the border of the selectized input does not change, is the plugin compatible with this class? or am I using it wrong?

My code: 

```
    <div class="form-group">
        @Html.LabelFor(x => x.id_tipotrafo)
     <select class="form-control is-invalid">
            <option value="Dist">Distribución</option>
            <option value="Pot">Potencia</option>
        </select>
        <div class="invalid-feedback">@Html.ValidationMessageFor(x => x.id_tipotrafo)</div>
    </div>
```

Thank you!

![selectize](https://user-images.githubusercontent.com/16128114/39923241-36cb5d7c-54f9-11e8-8b54-35e51922b7de.png)

**Comment by papakay** [comment]
@juanch0x thanks immensely for reaching out on this. I have added support for is-invalid class. Please kindly pull the changes and retry.

Thank you.

**Comment by juanch0x** [comment]
Hoooolly molly you are fast!!

It's working perfectly

Thanks so so much!

**Comment by papakay** [comment]
It's always a great privilege to be of help. Thank God.

Cheers.
